apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: liberty-git
spec:
  type: git
  params:
    - name: revision
      value: master
    - name: url
      value: https://github.com/devops4us/openliberty-tekton.git
---

apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: liberty-image-dev
spec:
  type: image
  params:
    - name: url
      value: us.icr.io/amsit/liberty-app:latest 
---

apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: liberty-image-stage
spec:
  type: image
  params:
    - name: url
      value: us.icr.io/amsit/liberty-app:stage