apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: liberty-pipeline
spec:
  resources:
    - name: liberty-git
      type: git
    - name: liberty-image-dev
      type: image
    - name: liberty-image-stage
      type: image

  params:
    - name: APP_NAME
      description: The name of the application
      default: 'liberty-tekton'      
    - name: APP_VERSION
      description: The version of the application
      default: '1.0'      
    - name: DEPLOY_PROJECT
      description: The project where you deploy the app
      default: 'env-dev'     
    - name: PROMOTE_PROJECT
      description: The project where you promote the app
      default: 'env-stage'

  tasks:
  - name: build
    taskRef:
      name: s2i-java-8
    resources:       
      inputs:
        - name: source
          resource: liberty-git
      outputs:
        - name: image
          resource: liberty-image-dev

  - name: deploy
    taskRef:
      name: deploy-liberty-app
    runAfter:
      - test
    params:
      - name: APP_NAME
        value: "$(params.APP_NAME)"
      - name: APP_VERSION
        value: "$(params.APP_VERSION)"  
      - name: DEPLOY_PROJECT
        value: "$(params.DEPLOY_PROJECT)"       
    resources:
      inputs:
        - name: image
          resource: liberty-image-dev

  - name: test
    taskRef:
      name: test-liberty-app
    runAfter:
      - build
    resources:
      inputs:
        - name: source
          resource: liberty-git

  - name: promote
    taskRef:
      name: promote-liberty-app
    runAfter:
      - deploy
    params:
      - name: APP_NAME
        value: "$(params.APP_NAME)"
      - name: APP_VERSION
        value: "$(params.APP_VERSION)"
      - name: DEPLOY_PROJECT
        value: "$(params.DEPLOY_PROJECT)"
      - name: PROMOTE_PROJECT
        value: "$(params.PROMOTE_PROJECT)"
    resources:
      inputs:
        - name: image
          resource: liberty-image-dev
      outputs:
        - name: image
          resource: liberty-image-stage